on: workflow_call

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - run: npm run build --if-present
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to raspberry pi
        uses: garygrossgarten/github-action-scp@release
        with:
          local: dist
          remote: home/max/Code/pocketbase/pb_data
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
