name: "Build & Deploy Client"
on: workflow_call

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - run: |
          npm install 
          npm run build --if-present
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: Deploy to raspberry pi
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "dist/assets/*.css,dist/assets/*.js,index.html,vite.svg"
          target: /home/max/Code/pocketbase/pb_public
